apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-manager-rolebinding
subjects:
- kind: User
  name: mahi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io

